<a href="https://colab.research.google.com/github/hemasphere/CS381/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hema Muni

CS 381

Homework 4

Question One

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

ls = []

for i in a:
  for j in b:
    if i == j and i not in ls:
      ls.append(i)

print(ls)

[2, 4]


Question Two

In [ ]:
a = np.array([np.arange(1, 16, 5), np.arange(2, 17, 5), np.arange(3, 18, 5),
          np.arange(4, 19, 5), np.arange(5, 20, 5)])

a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

Question Three

In [ ]:
flat_array = a.flatten('F')

flat_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Question Four

In [ ]:
a.T

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Question Five

(5, 3)

Question Six

In [ ]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

a = [i for i in a if i not in b]

#https://stackoverflow.com/questions/4211209/remove-all-the-elements-that-occur-in-one-list-from-another

print("a:", a)
print("b:", b)

a: [7, 15, 1, 8]
b: [14  6  3 11 19 12  5]


Question Seven

In [11]:
import pandas as pd
import numpy as np 
import statistics 

df = pd.read_excel("/content/Module6_Data.xlsx")
df

Year  New York City Population  \
0   1979.0                 7102100.0   
1   1980.0                 7071639.0   
2   1981.0                 7089241.0   
3   1982.0                 7109105.0   
4   1983.0                 7181224.0   
5   1984.0                 7234514.0   
6   1985.0                 7274054.0   
7   1986.0                 7319246.0   
8   1987.0                 7342476.0   
9   1988.0                 7353719.0   
10  1989.0                 7344175.0   
11  1990.0                 7335650.0   
12  1991.0                 7374501.0   
13  1992.0                 7428944.0   
14  1993.0                 7506166.0   
15  1994.0                 7570458.0   
16  1995.0                 7633040.0   
17  1996.0                 7697812.0   
18  1997.0                 7773443.0   
19  1998.0                 7858259.0   
20  1999.0                 7947660.0   
21  2000.0                 8008278.0   
22  2001.0                 8024963.5   
23  2002.0                 8041649.0   
24  2003.0                 8058334.5   
25  2004.0                 8075020.0   
26  2005.0                 8091705.5   
27  2006.0                 8108391.0   
28  2007.0                 8125076.5   
29  2008.0                 8141762.0   
30  2009.0                 8158447.5   
31  2010.0                 8175133.0   
32  2011.0                 8284098.0   
33  2012.0                 8361179.0   
34  2013.0                 8422460.0   
35  2014.0                 8471990.0   
36  2015.0                 8516502.0   
37  2016.0                 8537673.0   
38  2017.0                 8622698.0   

    NYC Consumption(Million gallons per day)  \
0                                     1512.0   
1                                     1506.0   
2                                     1309.0   
3                                     1382.0   
4                                     1424.0   
5                                     1465.0   
6                                     1326.0   
7                                     1351.0   
8                                     1447.0   
9                                     1484.0   
10                                    1402.0   
11                                    1424.0   
12                                    1469.0   
13                                    1369.0   
14                                    1368.5   
15                                    1357.7   
16                                    1325.7   
17                                    1297.9   
18                                    1205.5   
19                                    1219.5   
20                                    1237.2   
21                                    1240.4   
22                                    1184.0   
23                                    1135.6   
24                                    1093.7   
25                                    1099.5   
26                                    1138.0   
27                                    1069.0   
28                                    1114.0   
29                                    1098.0   
30                                    1007.5   
31                                    1039.0   
32                                    1021.0   
33                                    1009.1   
34                                    1006.1   
35                                     996.0   
36                                    1009.0   
37                                    1002.0   
38                                     990.2   

    Per Capita(Gallons per person per day)  
0                                    213.0  
1                                    213.0  
2                                    185.0  
3                                    194.0  
4                                    198.0  
5                                    203.0  
6                                    182.0  
7                                    185.0  
8                                    197.0  
9                                 

1. What is the maximum yearly NYC consumption of water in millions of gallons per day?


In [4]:
max_consumption = 0
for i in df["NYC Consumption(Million gallons per day)"]:
  if i > max_consumption:
    max_consumption = i

print(max_consumption)

1512.0


2. How many calendar years are represented within this data set? NumPy's shape command is one way to find out

In [10]:
np.shape(df)

(39, 4)

3. What is the mean and the standard deviation of the per capita daily water consumption?


In [12]:
statistics.mean(df["Per Capita(Gallons per person per day)"])

160.30769230769232

In [13]:
statistics.stdev(df["Per Capita(Gallons per person per day)"])

31.930973122258784

4. What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.


In [15]:
pop_diff = np.diff(df["New York City Population"])

print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
